### ISSUE TITLE
Failed to record call

### ISSUE THREAD

**Issue by hasan11222** [chenxiaolong/BCR#103]
Unable to retrieve audiorecod pointer For framecount()
![Screenshot_20220717-222524_MX_Player_Pro](https://user-images.githubusercontent.com/109313556/179884240-48ba64e2-c899-4202-b42d-55e7810c5d70.png)

Cant record call and have this error message...
 I am on lineageos 17.1 (android 10) . Using BCR 1.15

I try change some settings but nothing happened..

**Comment by chenxiaolong** [comment]
I believe that error is coming from Android itself. Can you grab a log file? You can do that by long pressing the version number in BCR (to switch to debug mode) and then try to record a call. It should create a log file in the output folder.

**Comment by hasan11222** [comment]
[20220726_124253.494+0430_out_+989171040485.log.txt](https://github.com/chenxiaolong/BCR/files/9187966/20220726_124253.494%2B0430_out_%2B989171040485.log.txt)

Thanks by your support...
Here is the log 🙏

**Comment by chenxiaolong** [comment]
```
java.lang.IllegalStateException: Unable to retrieve AudioRecord pointer for frameCount()
	at android.media.AudioRecord.native_get_buffer_size_in_frames(Native Method)
	at android.media.AudioRecord.getBufferSizeInFrames(AudioRecord.java:957)
	at com.chiller3.bcr.RecorderThread.recordUntilCancelled(RecorderThread.kt:8)
	at com.chiller3.bcr.RecorderThread.run(RecorderThread.kt:12)
```
Unfortunately, your device (or maybe device + ROM combination) does not support call recording. The error occurs because Android is not able to set up the `VOICE_CALL` audio stream for call recording.
