### ISSUE TITLE
Unable to retrieve AudioRecord pointer for frameCount()

### ISSUE THREAD

**Issue by Paco-grc** [chenxiaolong/BCR#200]
Hello,

When I pick up a call, the BCR v1.26 application systematically gives me the following message:

> Call recording failed
> Unable to retrieve AudioRecord pointer for frameCount()
> 
> primary:XXX.oga

I installed the BCR module through Magisk.
The application has all the permissions necessary for its operation (Contacts, Microphone and Phone).
I'm using LineageOS 18.1 (Android 11) on a Samsung Galaxy A5 2017 (SM-A520F).

Thanking you.

**Comment by owengo** [comment]
Hello, we have the same problem with 1.25
When enabling debug we have this:

the first error is: " android.media.AudioRecord: Error code -20 when initializing native AudioRecord object."

```
12-20 11:17:48.103  8570  9201 D RecorderThread/38: AudioRecord minimum buffer size: 4096
12-20 11:17:48.771  8570  9201 E AudioRecord: createRecord_l(27): AudioFlinger could not create record track, status: -22
12-20 11:17:48.771  8570  9201 E AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
12-20 11:17:48.773  8570  9201 E android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
12-20 11:17:48.783  8570  9201 D RecorderThread/38: Creating 20221220_111744.355+0100_in_<phone number>.oga with MIME type audio/ogg in content://com.android.externalstorage.documents/tree/primary%3ARecordings/document/primary%3ARecordings
12-20 11:17:48.854  8570  8570 D RecorderInCallService: onDetailsChanged: Call [id: TC@3, state: ACTIVE, details: [id: TC@3, state: ACTIVE, pa: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}, hdl: tel:**********78, hdlPres: 1, videoState: Audio Only, caps: [Capabilities: CAPABILITY_HOLD CAPABILITY_SUPPORT_HOLD CAPABILITY_MUTE CAPABILITY_CANNOT_DOWNGRADE_VIDEO_TO_AUDIO], props: [Properties:]]], [id: TC@3, state: ACTIVE, pa: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}, hdl: tel:**********78, hdlPres: 1, videoState: Audio Only, caps: [Capabilities: CAPABILITY_HOLD CAPABILITY_SUPPORT_HOLD CAPABILITY_MUTE CAPABILITY_CANNOT_DOWNGRADE_VIDEO_TO_AUDIO], props: [Properties:]]
12-20 11:17:48.934  8570  8570 I RecorderThread/38: Updated filename due to call details change: 20221220_111744.355+0100_in_<phone number>
12-20 11:17:48.934  8570  8570 D RecorderInCallService: handleStateChange: Call [id: TC@3, state: ACTIVE, details: [id: TC@3, state: ACTIVE, pa: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}, hdl: tel:**********78, hdlPres: 1, videoState: Audio Only, caps: [Capabilities: CAPABILITY_HOLD CAPABILITY_SUPPORT_HOLD CAPABILITY_MUTE CAPABILITY_CANNOT_DOWNGRADE_VIDEO_TO_AUDIO], props: [Properties:]]], null, 4
12-20 11:17:49.003  8570  9201 I RecorderThread/38: Successfully moved file:///storage/emulated/0/Android/data/com.chiller3.bcr/files/20221220_111744.355+0100_in_<phone number>.oga to content://com.android.externalstorage.documents/tree/primary:Recordings/document/primary:Recordings/20221220_111744.355+0100_in_<phone number>.oga
12-20 11:17:49.019  8570  9201 I RecorderThread/38: Keeping all existing files
12-20 11:17:49.020  8570  9201 E RecorderThread/38: Error during recording
12-20 11:17:49.020  8570  9201 E RecorderThread/38: java.lang.IllegalStateException: Unable to retrieve AudioRecord pointer for frameCount()
12-20 11:17:49.020  8570  9201 E RecorderThread/38: 	at android.media.AudioRecord.native_get_buffer_size_in_frames(Native Method)
12-20 11:17:49.020  8570  9201 E RecorderThread/38: 	at android.media.AudioRecord.getBufferSizeInFrames(AudioRecord.java:1220)
12-20 11:17:49.020  8570  9201 E RecorderThread/38: 	at com.chiller3.bcr.RecorderThread.recordUntilCancelled(RecorderThread.kt:53)
12-20 11:17:49.020  8570  9201 E RecorderThread/38: 	at com.chiller3.bcr.RecorderThread.run(RecorderThread.kt:148)
12-20 11:17:49.020  8570  9201 I RecorderThread/38: Recording thread completed
12-20 11:17:49.021  8570  9201 W RecorderInCallService: Recording failed: 38: 
```

**Comment by chenxiaolong** [comment]
The device (or the ROM/firmware) likely doesn't support call recording. This is almost always the case when you see `AudioRecord` in the error message.

> LineageOS 18.1 (Android 11) on a Samsung Galaxy A5 2017 (SM-A520F).

I'm not aware of any Samsung device where call recording works on LineageOS or any non-OneUI OS, unfortunately.

**Comment by Paco-grc** [comment]
Ok. If that's not possible, then I'll have to deal with it...
Thanks for your answer chenxiaolong.

**Comment by owengo** [comment]
Actually the "native" call recording app is working fine, but we can't automate it. We will try to install OneUI Android 9 on the 7 edge.
