### ISSUE TITLE
Crash when making a call

### ISSUE THREAD

**Issue by ghost** [chenxiaolong/BCR#282]
When I call someone, I get a notification that recording has started, and a moment later that the BCR app has crashed.
My phone model is Samsung Galaxy M52 5G (SM-M526BR/DS)
Magisk version: 25.2 (25200)
Here is crash.log.txt file (pastebin because the logs exceed the maximum number of characters per comment on github): https://pastebin.com/e8jB0nUM

**Comment by chenxiaolong** [comment]
Thanks for the info, @NLLAPPS! That sounds promising. The vector drawable I've been using for quick settings and notification icons has `android:tint="?attr/colorControlNormal"` and `android:fillColor="@android:color/white"`. I'll try dropping the (useless) tint and setting the color to a raw ARGB value.

---

@SandResidence Can you give this debug build a try? [BCR-1.38.r5.g4acb8c5-debugOpt.zip](https://github.com/chenxiaolong/BCR/files/11153286/BCR-1.38.r5.g4acb8c5-debugOpt.zip)

**Comment by SandResidence** [comment]
Okay, I've finally solved the problem!
Unfortunately, I forgot to install the .apk file that came with the Magisk module.
I removed the Magisk module, rebooted the phone, and then I installed the Magisk module and installed the .apk file.
After another reboot, it works like a charm.

**Comment by Bazoogle** [comment]
The old pastebin is now expired, but based on the quote I believe I am getting the same error with a different resource ID:
```
[Device Brand]: motorola
[Device Model]: motorola edge (2021)
[Display]: lineage_berlna-userdebug 14 AP2A.240905.003 f05164546c
[Android Version]: 14
[Android API Level]: 34
[System Locale]: en_US
[Process ID]: 23082
[User ID]: 0
[CPU ABI]: none
[Package Name]: com.chiller3.bcr
[Version Name]: 1.72
[Version Code]: 83968
[Target SDK]: 35
[Min SDK]: 28
[Error Type]: JVM
[Crash Time]: 2024-10-29T17:03:00.504
[Stack Trace]:
android.app.RemoteServiceException$BadForegroundServiceNotificationException: Bad notification(tag=null, id=265) posted from package com.chiller3.bcr, crashing app(uid=10211, pid=23082): Couldn't create icon StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.chiller3.bcr id=0x7f070093) visible user=0 )
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2220)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2520)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```
When I try to make a call, it crashes repeatedly, and actually makes it difficult to even end the call because the error popups are so quick.

I just tried disabling my notifications, and it worked. I was able to narrow it down to the "Background services" notification category that's causing the issue.
![BCR Notifcation Settings](https://github.com/user-attachments/assets/ca2fbe42-d195-4ad6-a7b3-b12933a4ab5b)
If I enable that category, the errors start, and if I disable the category, the errors stop.

**Comment by chenxiaolong** [comment]
@Bazoogle Do you have any root hiding modules installed? (Shamiko, etc.) Those usually cause this (Android can't access BCR's `.apk` to read the icon). If you want to keep those installed, a lot of folks have been able to work around the problem by extracting BCR's apk from the module zip and installing it normally.
