### ISSUE TITLE
Bug/Crash

### ISSUE THREAD

**Issue by Shidapu** [chenxiaolong/BCR#307]
FATAL EXCEPTION: main
Process: com.chiller3.bcr, PID: 26209
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chiller3.bcr/com.chiller3.bcr.SettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:676)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:6)
	at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:2)
	at com.chiller3.bcr.SettingsActivity.onCreate(Unknown Source:6)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	... 12 more

**Comment by chenxiaolong** [comment]
Closing this in favor of #303 so I can track the issue in one place.

Please see my comment in that thread: https://github.com/chenxiaolong/BCR/issues/303#issuecomment-1518895997
