### ISSUE TITLE
BCR App gone after Magisk 26.1 Update

### ISSUE THREAD

**Issue by g0w3st** [chenxiaolong/BCR#322]
POCO F3 / 14.0.7.0.TKHEUXM
Magisk 26.1
BCR 1.41

After Update to 26.1 from 25.2 the App is shown under Modules but disappears from the app drawer and is no longer working. 
removing and reinstalling did not change that.

Installing an older version prompted the following:
![Screenshot_2023-05-02-16-01-15-219_com topjohnwu magisk-edit](https://user-images.githubusercontent.com/132366944/235717245-42a1192f-870f-4ec4-b0df-d0a60861c7ee.jpg)

**Comment by chenxiaolong** [comment]
Is this happening on MIUI? Also, is this with the official Magisk 26.1 or a fork of it (eg. Magisk Delta)?

Please go to the logs tab in Magisk, hit the save button, and upload the logs here.

**Comment by g0w3st** [comment]
The log 
[magisk_log_2023-05-02T21.30.51.log](https://github.com/chenxiaolong/BCR/files/11377063/magisk_log_2023-05-02T21.30.51.log)

**Comment by kunago** [comment]
This is the crash log:
```
FATAL EXCEPTION: main
Process: com.chiller3.bcr, PID: 11231
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chiller3.bcr/com.chiller3.bcr.SettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3673)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3810)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:227)
	at android.os.Looper.loop(Looper.java:327)
	at android.app.ActivityThread.main(ActivityThread.java:7951)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:676)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:6)
	at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:2)
	at com.chiller3.bcr.SettingsActivity.onCreate(Unknown Source:6)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8269)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1398)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
	... 12 more
```

**Comment by g0w3st** [comment]
Official magisk, latest MIUI

**Comment by kunago** [comment]
Not sure if this is the same issue but it for sure is related to Magisk 26.1. I have a different phone brand and the app crashes immediately with the crash log posted above.

**Comment by chenxiaolong** [comment]
@g0w3st Thanks for the logs. Looks like Magisk 26.0's support for `overlayfs` might not be working properly. BCR previously had a workaround for this, which is likely why 1.40 works for you. Can you give this debug build a try? [BCR-1.41.r35.g3d90d22-debug.zip](https://github.com/chenxiaolong/BCR/files/11402470/BCR-1.41.r35.g3d90d22-debug.zip) It adds back the workaround.

@kunago Yep, your issue is #303, which has already been fixed and will be part of the upcoming 1.42 release.

**Comment by nikhilbadyal** [comment]
Latest update **1.42** working fine.

**Comment by g0w3st** [comment]
Hello, 
thanks for your effort. 1.42 works flawlessly again. BCR 1.40 was not working either. 
Very much appreciated!
All the very best!

**Comment by chenxiaolong** [comment]
Awesome, glad to hear it!
