### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by chengnan049** [chenxiaolong/BCR#439]
I don't remember what I did but I can prove this.

I'm using  Magisk Alpha 26301 with Shamiko

BCR is the latest version, I have been reinstalling the BCR module but it didn't work.

Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
```
[Device Brand]: Redmi
[Device Model]: 22101317C
[Display]: TKQ1.221013.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: en_US
[Process ID]: 3206
[CPU ABI]: none
[Package Name]: com.chiller3.bcr
[Version Name]: 1.52
[Version Code]: 78848
[Error Type]: JVM
[Crash Time]: 2023-10-05T13:08:37.230
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:275)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6990)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8289)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by chenxiaolong** [comment]
Hmm, `updateLocaleListFromAppContext` happens before the app runs, when the system is trying to load the languages. I did some searching for that error and it seems like it's relatively common on Xiaomi devices and some OnePlus devices, but I didn't find any explanations for why it might be happening or any potential workarounds.

I don't know how to fix this.

**Comment by chengnan049** [comment]
In addition, my room is MIUI 14 EEA Global, my phone is Redmi Note 12 5G, the latest version is still crashed. The app is the default icon, the name in the launcher is the app package name.

**Comment by chenxiaolong** [comment]
> The app is the default icon, the name in the launcher is the app package name.

That seems like some system components are not able to read `/system/priv-app/com.chiller3.bcr/app-release.apk`.

It might be worth trying regular Magisk without Shamiko to see if that works. Unfortunately, both Magisk Alpha and Shamiko seem to not be open source--I don't know if they do something different when handling Magisk modules.

**Comment by limon** [comment]
los20 + kernelsu + shamiko, crash as well. i have to disable shamiko now.

**Comment by chengnan049** [comment]
> > The app is the default icon, the name in the launcher is the app package name.
> 
> That seems like some system components are not able to read `/system/priv-app/com.chiller3.bcr/app-release.apk`.
> 
> It might be worth trying regular Magisk without Shamiko to see if that works. Unfortunately, both Magisk Alpha and Shamiko seem to not be open source--I don't know if they do something different when handling Magisk modules.

Alpha has a dedicated Shamiko, which is updated on its author's Telegram channel, and BCR works normally in blacklist mode

**Comment by chengnan049** [comment]
可以使用 爱玩机工具箱 内的 唤醒 Root 权限，来使得 BCR 获得 Root 权限，获得后在 Shamoko 白名单模式下也能正常工作

**Comment by Jacoblightning** [comment]
Having the exact same issue on my pixel 7a. I'm using kitsune magisk and a few other modules.

**Comment by chengnan049** [comment]
fixed. MKSU 32303
