### ISSUE TITLE
Crashing, recordings without sound 

### ISSUE THREAD

**Issue by msalah-kw** [chenxiaolong/BCR#475]
BOARD=taro
SOC_MANUFACTURER=QTI
CPU_ABI2=
HOST=SWDK6005
versionName=3.0.81
IS_TREBLE_ENABLED=true
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@9b8215f
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=true
IS_USERDEBUG=false
DISPLAY=S908EXXU7ZWJ3_Dr.Ketan_UB2_XDA
HW_TIMEOUT_MULTIPLIER=1
IS_ARC=false
SUPPORTED_ABIS=[Ljava.lang.String;@c0b57ac
FINGERPRINT=samsung/b0qxxx/b0q:14/UP1A.231005.007/S908EXXU7ZWJ3:user/release-keys
MODEL_FOR_ATTESTATION=SM-S908E
PRODUCT=b0qxxx
DEVICE_FOR_ATTESTATION=unknown
BRAND_FOR_ATTESTATION=samsung
ID=UP1A.231005.007
SOC_MODEL=SM8450
TYPE=user
MANUFACTURER_FOR_ATTESTATION=samsung
SERIAL=unknown
IS_ENG=false
DEVICE=b0q
ODM_SKU=unknown
TIME=1696492694000
IS_USER=true
MODEL=SM-S908E
PRODUCT_FOR_ATTESTATION=unknown
MANUFACTURER=samsung
USER=dpi
versionCode=20231116
BRAND=samsung
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@86605fe
HARDWARE=qcom
IS_DEBUGGABLE=false
BOOTLOADER=S908EXXU7ZWJ3
RADIO=unknown
TAG=Build
UNKNOWN=unknown
IS_EMULATOR=false
SKU=unknown
TAGS=release-keys
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=96, result=0, data=null} to activity {com.wn.app.np/player.normal.np.activity.NPMainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6062)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6101)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8892)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
	at org.bouncycastle.x509.⁣⁤⁠⁠⁠⁣⁤⁤⁣⁤⁤⁤⁣⁤⁠⁠⁤⁣⁣⁣⁣⁣⁠⁣⁤⁠⁠⁣⁠⁠⁠⁣⁣⁤.⁣⁤⁠⁠⁠⁣⁤⁤⁣⁤⁤⁤⁣⁤⁠⁠⁤⁤⁠⁤⁤⁣⁤⁠⁠⁣(Unknown Source:8)
	at player.normal.np.activity.NPMainActivity.onActivityResult(Unknown Source:261)
	at android.app.Activity.dispatchActivityResult(Activity.java:9315)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6055)
	... 13 more
java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
	at org.bouncycastle.x509.⁣⁤⁠⁠⁠⁣⁤⁤⁣⁤⁤⁤⁣⁤⁠⁠⁤⁣⁣⁣⁣⁣⁠⁣⁤⁠⁠⁣⁠⁠⁠⁣⁣⁤.⁣⁤⁠⁠⁠⁣⁤⁤⁣⁤⁤⁤⁣⁤⁠⁠⁤⁤⁠⁤⁤⁣⁤⁠⁠⁣(Unknown Source:8)
	at player.normal.np.activity.NPMainActivity.onActivityResult(Unknown Source:261)
	at android.app.Activity.dispatchActivityResult(Activity.java:9315)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6055)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6101)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8892)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by chenxiaolong** [comment]
Are you running a debloated ROM of some sort? The crashes you posted are coming from Android itself.

**Comment by msalah-kw** [comment]
Yes it's debloated rom
How can I send u the logs?

**Comment by chenxiaolong** [comment]
If you're able to grab a logcat immediately after trying to record a call, I might be able to find out which components are missing.

**Comment by msalah-kw** [comment]
Excuse me, how can I grab it?

**Comment by chenxiaolong** [comment]
If you're familiar with adb, the easiest way is to run `adb logcat -d > logcat.txt`. Otherwise, you can try using a logcat app like https://f-droid.org/en/packages/com.f0x1d.logfox/.

**Comment by msalah-kw** [comment]
FATAL EXCEPTION: main
Process: com.chiller3.bcr, PID: 29651
android.app.RemoteServiceException$BadForegroundServiceNotificationException: Bad notification(tag=null, id=11) posted from package com.chiller3.bcr, crashing app(uid=10341, pid=29651): Couldn't create icon StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.chiller3.bcr id=0x7f070093) visible user=0 )
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2292)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8892)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by chenxiaolong** [comment]
Thanks for the log.

> Couldn't create icon StatusBarIcon

Unfortunately, I have absolutely no idea why your ROM doesn't like BCR's icon.
