### ISSUE TITLE
crash.log.tst

### ISSUE THREAD

**Issue by haiahaia** [chenxiaolong/BCR#478]
--------- beginning of main
12-25 10:50:37.069 18266 18266 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@5f5f360
12-25 10:50:37.167 18266 18294 I Adreno  : QUALCOMM build                   : 4daeac4, I85e9875322
12-25 10:50:37.167 18266 18294 I Adreno  : Build Date                       : 06/01/19
12-25 10:50:37.167 18266 18294 I Adreno  : OpenGL ES Shader Compiler Version: EV031.25.03.04
12-25 10:50:37.167 18266 18294 I Adreno  : Local Branch                     : 
12-25 10:50:37.167 18266 18294 I Adreno  : Remote Branch                    : 
12-25 10:50:37.167 18266 18294 I Adreno  : Remote Branch                    : 
12-25 10:50:37.167 18266 18294 I Adreno  : Reconstruct Branch               : 
12-25 10:50:37.167 18266 18294 I Adreno  : Build Config                     : S L 6.0.7 AArch64
12-25 10:50:37.173 18266 18294 I Adreno  : PFP: 0x005ff112, ME: 0x005ff066
12-25 10:50:37.175 18266 18294 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
12-25 10:50:37.175 18266 18294 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
12-25 10:50:37.175 18266 18294 I OpenGLRenderer: Initialized EGL, version 1.4
12-25 10:50:37.176 18266 18294 D OpenGLRenderer: Swap behavior 2
12-25 10:51:50.108 18266 18266 D AndroidRuntime: Shutting down VM
--------- beginning of crash
12-25 10:51:50.109 18266 18266 E AndroidRuntime: FATAL EXCEPTION: main
12-25 10:51:50.109 18266 18266 E AndroidRuntime: Process: com.chiller3.bcr, PID: 18266
12-25 10:51:50.109 18266 18266 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0xc2 }
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2014)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4587)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(Unknown Source:0)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at androidx.activity.ComponentActivity$1.onLaunch(Unknown Source:284)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at androidx.fragment.app.Fragment$10.launch(Unknown Source:44)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at androidx.fragment.app.Fragment$10.launch(Unknown Source:92)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at com.chiller3.bcr.settings.OutputDirectoryBottomSheetFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:76)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at android.view.View.performClick(View.java:6597)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:9)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6574)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25889)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6746)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-25 10:51:50.109 18266 18266 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-25 10:51:50.111 18266 18266 D OutputDirUtils: Creating crash.log with MIME type text/plain in file:///storage/emulated/0/Android/data/com.chiller3.bcr/files
12-25 10:51:50.116 18266 18266 E RecorderApplication: Saving logcat to file:///storage/emulated/0/Android/data/com.chiller3.bcr/files/crash.log.txt due to uncaught exception in Thread[main,5,main]
12-25 10:51:50.116 18266 18266 E RecorderApplication: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0xc2 }
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2014)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at android.app.Activity.startActivityForResult(Activity.java:4587)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(Unknown Source:0)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at androidx.activity.ComponentActivity$1.onLaunch(Unknown Source:284)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at androidx.fragment.app.Fragment$10.launch(Unknown Source:44)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at androidx.fragment.app.Fragment$10.launch(Unknown Source:92)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at com.chiller3.bcr.settings.OutputDirectoryBottomSheetFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:76)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at android.view.View.performClick(View.java:6597)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:9)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at android.view.View.performClickInternal(View.java:6574)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at android.view.View.access$3100(View.java:778)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at android.view.View$PerformClick.run(View.java:25889)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at android.os.Handler.handleCallback(Handler.java:873)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at android.os.Looper.loop(Looper.java:193)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at android.app.ActivityThread.main(ActivityThread.java:6746)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at java.lang.reflect.Method.invoke(Native Method)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-25 10:51:50.116 18266 18266 E RecorderApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

How to resolve this issue？

**Comment by chenxiaolong** [comment]
That's happening because Android's `DocumentsUI` system app isn't installed or enabled. Please make sure your ROM didn't remove that component (eg. if it's debloated) and that you have no Magisk modules that disabled it (eg. the MiXplorer module).

**Comment by haiahaia** [comment]
Thank you for your response. However, I just downloaded this app and tried to run it, and then the above-mentioned log appeared. How should I resolve this issue?

**Comment by chenxiaolong** [comment]
You'll have to find out how to reenable DocumentsUI in your ROM. DocumentsUI is Android's system file picker and BCR can't work without it. In the app list, it might be called "Files" or something similar instead of DocumentsUI.

**Comment by haiahaia** [comment]
Could its name be '文件管理器'? I only see this one related to files in my applications, or is it hidden in a way that I can't see through the usual methods?

**Comment by chenxiaolong** [comment]
That seems possible. On my device, it just shows up as `Files`. It should be listed in the apps section of Android's settings, but might need the "show system apps" option to be enabled.

If you're familiar with adb, you can also try enabling it this way:

```
adb shell pm enable com.android.documentsui
```
