### ISSUE TITLE
can not use BCR with lineageos

### ISSUE THREAD

**Issue by nguoido** [chenxiaolong/BCR#527]
4-15 16:34:18.715 10931 10931 D OutputDirUtils: Creating crash.log with MIME type text/plain in file:///storage/emulated/0/Android/data/com.chiller3.bcr/files
04-15 16:34:18.723 10931 10931 E RecorderApplication: Saving logcat to file:///storage/emulated/0/Android/data/com.chiller3.bcr/files/crash.log.txt due to uncaught exception in Thread[main,5,main]
04-15 16:34:18.723 10931 10931 E RecorderApplication: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0xc2 }
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2239)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.app.Activity.startActivityForResult(Activity.java:5615)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(Unknown Source:0)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at androidx.activity.ComponentActivity$1.onLaunch(Unknown Source:284)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at androidx.fragment.app.Fragment$10.launch(Unknown Source:44)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at androidx.fragment.app.Fragment$10.launch(Unknown Source:92)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at com.chiller3.bcr.settings.OutputDirectoryBottomSheetFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:76)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.view.View.performClick(View.java:7658)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:9)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.view.View.performClickInternal(View.java:7635)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.view.View$PerformClick.run(View.java:30167)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.os.Handler.handleCallback(Handler.java:958)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.os.Looper.loopOnce(Looper.java:205)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.os.Looper.loop(Looper.java:294)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at java.lang.reflect.Method.invoke(Native Method)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
04-15 16:34:18.723 10931 10931 E RecorderApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
04-15 16:34:18.736     0     0 I logd    : logdr: UID=10238 GID=10238 PID=10965 n tail=0 logMask=99 pid=0 start=0ns deadline=0ns
04-15 16:34:18.768 10931 10931 I OutputDirUtils: Successfully moved file:///storage/emulated/0/Android/data/com.chiller3.bcr/files/crash.log.txt to file:///storage/emulated/0/Android/data/com.chiller3.bcr/files/crash.log.txt
04-15 16:34:18.773  1598 10968 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
04-15 16:34:18.774  1598  2707 W ActivityTaskManager:   Force finishing activity com.chiller3.bcr/.settings.SettingsActivity
04-15 16:34:18.775  2243  2285 V WindowManagerShell: Transition requested: android.os.BinderProxy@d47bcb7 TransitionRequestInfo { type = 2, triggerTask = null, remoteTransition = null, displayChange = null, flags = 16 }
04-15 16:34:18.786  1598  1758 I ActivityManager: Showing crash dialog for package com.chiller3.bcr u0
04-15 16:34:18.825  1598  1758 D CoreBackPreview: Window{fb5a62b u0 Application Error: com.chiller3.bcr}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@dc82e59, mPriority=0, mIsAnimationCallback=false}
04-15 16:34:18.832  1598  3953 E OpenGLRenderer: Unable to match the desired swap behavior.
04-15 16:34:18.850  1129  1129 I BpBinder: onLastStrongRef automatically unlinking death recipients: 
04-15 16:34:19.276  1598  1760 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{697f5dd u0 com.chiller3.bcr/.settings.SettingsActivity t3679 f}}
04-15 16:34:19.280  1598  1760 W ActivityTaskManager: Activity pause timeout for ActivityRecord{697f5dd u0 com.chiller3.bcr/.settings.SettingsActivity t3679 f}}
04-15 16:34:19.286  1598  3947 D OomAdjuster: Not killing cached processes
04-15 16:34:19.289  1598  3947 W ProcessStats: Tracking association SourceState{ecef1da com.google.android.googlequicksearchbox:search/10156 BTop #6212} whose proc state 2 is better than process ProcessState{b43fbe1 com.google.android.googlequicksearchbox:interactor/10156 pkg=com.google.android.googlequicksearchbox} proc state 4 (240 skipped)

**Comment by chenxiaolong** [comment]
Thanks for the log. The root cause is this:
```
 04-15 16:34:18.723 10931 10931 E RecorderApplication: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0xc2 }
```
It means the system file picker is disabled. Please reenable it from Android's Settings -> Apps (it's likely called `Files` or `DocumentsUI`).

Some Magisk modules will also break the system file picker, like the MiXplorer module. If you have a module like this installed, please disable or remove it.
