### ISSUE TITLE
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{63426e1 u0 com.chiller3.bcr/.DirectBootMigrationService c:com.chiller3.bcr}

### ISSUE THREAD

**Issue by selfmusing** [chenxiaolong/BCR#574]
I included latest BCR in my custom rom & now I'm getting this error after every reboot :

Generated by AppErrorsTracking 1.3-b497173(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: Redmi Note 7 Pro
[Display]: AP2A.240705.005
[Android Version]: 14
[Android API Level]: 34
[System Locale]: en_US
[Process ID]: 9858
[User ID]: 0
[CPU ABI]: none
[Package Name]: com.chiller3.bcr
[Version Name]: 1.68
[Version Code]: 82944
[Target SDK]: 34
[Min SDK]: 28
[Error Type]: JVM
[Crash Time]: 2024-08-01T18:29:27.312
[Stack Trace]:
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{63426e1 u0 com.chiller3.bcr/.DirectBootMigrationService c:com.chiller3.bcr}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2243)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2214)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2520)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8590)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by chenxiaolong** [comment]
Can you grab a full logcat immediately after the crash and upload that?

`DirectBootMigrationService` unconditionally calls `startForeground()`, so I'm not quite sure why it's complaining about that.

**Comment by selfmusing** [comment]
> Can you grab a full logcat immediately after the crash and upload that?
> 
> `DirectBootMigrationService` unconditionally calls `startForeground()`, so I'm not quite sure why it's complaining about that.

Okay, I'll try but it's strange that now I'm not getting these crashes anymore..
It was only happened a few times after flashing the latest rom update.
