### ISSUE TITLE
BCR Module crashes camera video recording 

### ISSUE THREAD

**Issue by MuhammadKasimov** [chenxiaolong/BCR#614]

**Comment by chenxiaolong** [comment]
Sorry, I can't help without any details provided.

Please grab a logcat right after the crash and upload that.

**Comment by SaganVadim** [comment]
```
type: crash
osVersion: Redmi/veux_global/veux:13/TKQ1.221114.001/V816.0.9.0.TKCMIXM:user/release-keys
package: com.android.camera:450030900
process: com.android.camera
processUptime: 1602 + 70 ms

io.reactivex.exceptions.OnErrorNotImplementedException: Error retrieving camcorder profile params
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:2)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:1)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:2)
	at io.reactivex.internal.operators.single.SingleDetach$DetachSingleObserver.onError(SingleDetach.java:4)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:1)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:2)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:1)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8732)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: java.lang.RuntimeException: Error retrieving camcorder profile params
	at android.media.CamcorderProfile.native_get_camcorder_profile(Native Method)
	at android.media.CamcorderProfile.get(CamcorderProfile.java:528)
	at com.android.camera.lib.compatibility.util.CompatibilityUtils.fetchCamcorderProfile(CompatibilityUtils.java:3)
	at com.android.camera.module.video.UserRecordSetting.fetchProfile(UserRecordSetting.java:1)
	at com.android.camera.module.video.UserRecordSetting.readVideoPreferences(UserRecordSetting.java:3)
	at com.android.camera.module.VideoModule.readVideoPreferences(VideoModule.java:1)
	at com.android.camera.module.VideoModule.onCameraOpened(VideoModule.java:7)
	at com.android.camera.module.VideoModule.onCreate(VideoModule.java:14)
	at com.android.camera.module.BaseModule.onGLAndCameraReady(BaseModule.java:1)
	at com.android.camera.module.loader.FunctionModuleSetup.apply(FunctionModuleSetup.java:33)
	at com.android.camera.module.loader.FunctionModuleSetup.apply(FunctionModuleSetup.java:1)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:1)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:3)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:3)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at com.xiaomi.camera.rx.CameraSchedulers$2.run(CameraSchedulers.java:3)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by chenxiaolong** [comment]
That's interesting. Sadly, I have no idea what could possibly cause that. BCR doesn't even run in the background until you're in a call and the Magisk module doesn't touch any other app's files.
