### ISSUE TITLE
(crash): DirectBootMigration crash due to background service restriction

### ISSUE THREAD

**Issue by TogoFire** [chenxiaolong/BCR#634]
Rom: VoltageOS 4.0 A15.
Device: Oneplus9
[BCR Version 1.74](https://github.com/chenxiaolong/BCR/releases/tag/v1.74)

Log:
https://bin.cyberknight777.dev/gMWP/raw
type: crash
osVersion: OnePlus/OnePlus9/OnePlus9:14/UKQ1.230924.001/R.1a46f9a_1-1:user/release-keys
package: com.chiller3.bcr:84480
process: com.chiller3.bcr
processUptime: 60 + 30 ms

java.lang.RuntimeException: Unable to start receiver com.chiller3.bcr.DirectBootMigrationReceiver: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.chiller3.bcr/.DirectBootMigrationService }: app is in background uid UidRecord{3e7c6ee u0a198 RCVR bg:+44ms idle change:uncachedprocstate procs:0 seq(4322,4321)} caps=-------
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4792)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8732)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.chiller3.bcr/.DirectBootMigrationService }: app is in background uid UidRecord{3e7c6ee u0a198 RCVR bg:+44ms idle change:uncachedprocstate procs:0 seq(4322,4321)} caps=-------
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2005)
	at android.app.ContextImpl.startService(ContextImpl.java:1960)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at com.chiller3.bcr.DirectBootMigrationReceiver.onReceive(Unknown Source:29)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4783)
	... 9 more

It happens sometimes.

**Comment by chenxiaolong** [comment]
Hmm, this is probably caused by OnePlus' aggressive battery optimizations and there's likely nothing I can do to work around it.

Try disabling battery optimizations for BCR and see if that fixes it.

---

BCR supports recording calls before the device is first unlocked after a reboot. Because the storage is not decrypted yet, BCR has to store the recordings to a temporary directory. After unlocking the device for the first time, the `DirectBootMigrationReceiver` (from the crash) is what moves files from the temporary directory to the output directory.

If you don't care about this feature, you can just ignore the crash. (The process can also be manually triggered by long pressing BCR's version number and selecting the `Migrate direct boot recordings` option.)

**Comment by TogoFire** [comment]
> Hmm, this is probably caused by OnePlus' aggressive battery optimizations and there's likely nothing I can do to work around it.
> 
> Try disabling battery optimizations for BCR and see if that fixes it.
> 
> BCR supports recording calls before the device is first unlocked after a reboot. Because the storage is not decrypted yet, BCR has to store the recordings to a temporary directory. After unlocking the device for the first time, the `DirectBootMigrationReceiver` (from the crash) is what moves files from the temporary directory to the output directory.
> 
> If you don't care about this feature, you can just ignore the crash. (The process can also be manually triggered by long pressing BCR's version number and selecting the `Migrate direct boot recordings` option.)

Okay. thx.
