### ISSUE TITLE
Direct boot calls save to in_progress: failed to migrate recordings

### ISSUE THREAD

**Issue by FaridZelli** [chenxiaolong/BCR#643]
Device: Apollo (Mi 10T Pro)
ROM: LineageOS 21-20241221-NIGHTLY-apollon

Direct boot calls save to /data/user_de/0/com.chiller3.bcr/files/in_progress and fail to migrate. The files playback normally.

Logcat:
```
12-30 02:12:50.958 12746 12746 I DirectBootMigrationService: Starting direct boot file migration
12-30 02:12:50.960 12746 13846 I DirectBootMigrationService: 0 files to migrate
12-30 02:12:50.960 12746 13846 I DirectBootMigrationService: 0 succeeded, 0 failed
12-30 02:12:52.854 12746 12746 D DirectBootMigrationService: Stopping service
```

This is while there are playable *.oga files present in /data/user_de/0/com.chiller3.bcr/files/in_progress.
  
Copying a file over to /data/user_de/0/com.chiller3.bcr/files/completed manually results in the following errors:
```
12-30 02:25:13.089 13836 13836 I DirectBootMigrationService: Starting direct boot file migration
12-30 02:25:13.091 13836 15881 I DirectBootMigrationService: 1 files to migrate
12-30 02:25:13.101 13836 15881 W OutputDirUtils: Failed to efficiently move fi<...>ga to fi<...>es
12-30 02:25:13.101 13836 15881 D OutputDirUtils: Creating 20<...>03 with MIME type audio/ogg in fi<...>es
12-30 02:25:13.102 13836 15881 W OutputDirUtils: Failed to move file; using fallback path
12-30 02:25:13.102 13836 15881 W OutputDirUtils: java.io.FileNotFoundException: open failed: EACCES (Permission denied)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:361)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:237)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1853)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1689)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1635)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: 	at com.chiller3.bcr.output.OutputDirUtils.openFile(Unknown Source:23)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: 	at com.chiller3.bcr.output.OutputDirUtils.move(Unknown Source:291)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: 	at com.chiller3.bcr.output.OutputDirUtils.tryMoveToOutputDir(Unknown Source:51)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: 	at com.chiller3.bcr.DirectBootMigrationService.migrateFiles(Unknown Source:406)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: 	at com.chiller3.bcr.DirectBootMigrationService$$ExternalSyntheticLambda0.run(Unknown Source:16)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: 	at java.lang.Thread.run(Thread.java:1012)
12-30 02:25:13.102 13836 15881 W OutputDirUtils: Failed to efficiently move fi<...>ga to fi<...>es
12-30 02:25:13.102 13836 15881 D OutputDirUtils: Creating ER<...>03 with MIME type audio/ogg in fi<...>es
12-30 02:25:13.103 13836 15881 E OutputDirUtils: Failed to move fi<...>ga to androidx.documentfile.provider.RawDocumentFile@e514007
12-30 02:25:13.103 13836 15881 E OutputDirUtils: java.io.FileNotFoundException: open failed: EACCES (Permission denied)
12-30 02:25:13.103 13836 15881 E OutputDirUtils: 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:361)
12-30 02:25:13.103 13836 15881 E OutputDirUtils: 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:237)
12-30 02:25:13.103 13836 15881 E OutputDirUtils: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1853)
12-30 02:25:13.103 13836 15881 E OutputDirUtils: 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1689)
12-30 02:25:13.103 13836 15881 E OutputDirUtils: 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1635)
12-30 02:25:13.103 13836 15881 E OutputDirUtils: 	at com.chiller3.bcr.output.OutputDirUtils.openFile(Unknown Source:23)
12-30 02:25:13.103 13836 15881 E OutputDirUtils: 	at com.chiller3.bcr.output.OutputDirUtils.move(Unknown Source:291)
12-30 02:25:13.103 13836 15881 E OutputDirUtils: 	at com.chiller3.bcr.output.OutputDirUtils.tryMoveToOutputDir(Unknown Source:87)
12-30 02:25:13.103 13836 15881 E OutputDirUtils: 	at com.chiller3.bcr.DirectBootMigrationService.migrateFiles(Unknown Source:406)
12-30 02:25:13.103 13836 15881 E OutputDirUtils: 	at com.chiller3.bcr.DirectBootMigrationService$$ExternalSyntheticLambda0.run(Unknown Source:16)
12-30 02:25:13.103 13836 15881 E OutputDirUtils: 	at java.lang.Thread.run(Thread.java:1012)
12-30 02:25:13.103 13836 15881 I DirectBootMigrationService: 0 succeeded, 1 failed
12-30 02:25:13.106 13836 13836 D DirectBootMigrationService: Stopping service
```
[20241230_013501.log.txt](https://github.com/user-attachments/files/18271222/20241230_013501.log.txt)
[logcat.log.txt](https://github.com/user-attachments/files/18271223/logcat.log.txt)
[logcat2.log.txt](https://github.com/user-attachments/files/18271224/logcat2.log.txt)

**Comment by chenxiaolong** [comment]
Thanks for the logs!

The initial issue where files weren't moved from `in_progress/` to `completed/` is caused by BCR not being allowed to query contacts (for computing the final filename) before the device is first unlocked:

```
12-30 01:35:25.339  3934  4064 W ActivityThread: Failed to find provider info for com.android.contacts (user not unlocked)
12-30 01:35:25.339  3934  4064 E RecorderThread/151: Error during recording
12-30 01:35:25.339  3934  4064 E RecorderThread/151: java.io.IOException: Query returned null cursor: content://com.android.contacts/phone_lookup_enterprise/%2B[REDACTED]?sip=false
```

I believe this is a regression introduced in version 1.73. This should be an easy fix for the upcoming 1.75 release.

As for the issue where the files failed to be moved from `completed/` to the output directory:

```
12-30 02:25:13.103 13836 15881 E OutputDirUtils: java.io.FileNotFoundException: open failed: EACCES (Permission denied)
```

I think this might've been caused by the file copy. I'm guessing the copied files ended up being owned as root, so BCR can't open them. Could you check the permissions on those?

(BCR doesn't actually have root privileges. It only uses root as a mechanism to install as a system app.)

**Comment by chenxiaolong** [comment]
The regression should be fixed by #645, which will be included in the upcoming 1.75 release.

**Comment by FaridZelli** [comment]
> The regression should be fixed by #645, which will be included in the upcoming 1.75 release.

Thank you so much Andrew, it works like a charm! I admire the overall polish of this update, especially with the new rules interface.
